doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Student:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Enrollment/Infrastructure/Persistence'
                prefix: 'App\Student\Infrastructure\Persistence'
                alias: Enrollment
            App\Course:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Course/Infrastructure/Persistence'
                prefix: 'App\Course\Infrastructure\Persistence'
                alias: Course
            App\Enrollment:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Enrollment/Infrastructure/Persistence'
                prefix: 'App\Enrollment\Infrastructure\Persistence'
                alias: Enrollment
            App\Exam:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Exam/Infrastructure/Persistence'
                prefix: 'App\Exam\Infrastructure\Persistence'
                alias: Exam
            App\Grade:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Grade/Infrastructure/Persistence'
                prefix: 'App\Grade\Infrastructure\Persistence'
                alias: Grade
