doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            School\Student:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Enrollment/Infrastructure/Persistence'
                prefix: 'School\Student\Infrastructure\Persistence'
                alias: Enrollment
            School\Course:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Course/Infrastructure/Persistence'
                prefix: 'School\Course\Infrastructure\Persistence'
                alias: Course
            School\Enrollment:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Enrollment/Infrastructure/Persistence'
                prefix: 'School\Enrollment\Infrastructure\Persistence'
                alias: Enrollment
            School\Exam:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Exam/Infrastructure/Persistence'
                prefix: 'School\Exam\Infrastructure\Persistence'
                alias: Exam
            School\Grade:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Grade/Infrastructure/Persistence'
                prefix: 'School\Grade\Infrastructure\Persistence'
                alias: Grade
