version: '3'

services:
  mysql:
    container_name: school-mysql
    image: mysql:8.0.23
    ports:
      - "3363:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=school_db
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - ./container/data:/docker-entrypoint-initdb.d

  php:
    container_name: school-php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - .:/app:delegated
    env_file:
      - .env
    depends_on:
      - mysql
    command: symfony serve --port=8080 --no-tls

