version: '3'

services:
  mysql:
    container_name: school-mysql
    image: mysql:8.0.23
    ports:
      - "3363:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=school_db
    command: ["--default-authentication-plugin=mysql_native_password"]
