# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Configure
    _instanceof:
        School\Shared\Domain\Bus\Event\DomainEventSubscriber:
            tags: [ 'school.domain_event_subscriber' ]

        School\Shared\Domain\Bus\Command\CommandHandler:
            tags: [ 'school.command_handler' ]

        School\Shared\Domain\Bus\Query\QueryHandler:
            tags: [ 'school.query_handler' ]

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    School\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../app/Controller/'
        tags: ['controller.service_arguments']

    App\:
        resource: '../app/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # -- APP DEFINITIONS --
    # Command/Query Handlers
    School\Shared\Infrastructure\Bus\Command\InMemorySymfonyCommandBus:
        arguments: [!tagged school.command_handler]

    School\Shared\Infrastructure\Bus\Query\InMemorySymfonyQueryBus:
        arguments: [!tagged school.query_handler]
        lazy: true

    # Events
    School\Shared\Infrastructure\Bus\Event\InMemory\InMemorySymfonyEventBus:
        arguments: [!tagged school.domain_event_subscriber]
        lazy: true
